name: build

on:
  workflow_dispatch:
  push:
    tags:        
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore nupkg/nupkg.sln
    - name: Build
      run: dotnet build nupkg/nupkg.sln --no-restore --configuration Release
    #- name: Test
     # run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack nupkg/nupkg.sln -o temp_nupkg --configuration Release
    - name: Push Packages
      run: dotnet nuget push ./temp_nupkg/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
